#!/bin/bash

# Version (DO NOT CHANGE THIS)
changelog_Current="1.0.3"

shopt -s nocasematch

function checkChangelog {

    curl -s https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/$Branch/extra_files/changelog.txt -o changelog.txt

    source changelog.txt

    echo -e; echo -e "$CYAN Date: $RESET $Date"
    sleep 1s
    echo -e "$Changelog"

    if [[ $SaveChangelog =~ true ]]; then
        cd ../
            if [ ! -f changelog.txt ]; then
                echo "" >> changelog.txt
            fi
        spacers=`echo; echo "===================================="`
        copyInformation=`echo "$spacers"; echo; echo "Current Date: $Date"; echo; echo "Changelog Information:"; echo "$Changelog"; echo`
        echo "$copyInformation"|cat - changelog.txt > /tmp/out && mv /tmp/out changelog.txt
    fi
    
    rm changelog.txt
}
