#!/bin/bash

# Version Checker 
installserver_Current="1.2.0"

source ../version.ini
source ../configuration.ini
source formatting.ini

function installServer {

    source _functions

    installSteam

    # Install Server Files
    echo -e "$YELLOW Now installing game server. This may take a while. $RESET"
    runSteam 1

    echo -e "$GREEN Complete. Exiting. $RESET"
    echo -e " You may now start the server with $GREEN ./arkserver.sh start $RESET"

}
