#!/bin/bash

# Version Checker 
version="1.1.8"

source ../version.ini
source ../configuration.ini
source formatting.ini

# Version Checker
echo -e; echo -e "$YELLOW Checking version with github. $RESET"
if [ $version != $stopserver ]; then
    echo -e " Script update available! (Install Script)"
    echo -e; echo -e "$YELLOW Downloading script file. $RESET"
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/installserver -o installserver -#
    echo -e; echo -e "$GREEN File overwritten. Please restart the script. $RESET"
    exit 0
else
    echo -e " Up to date!"; echo -e
    sleep 1s
fi


cd ../
# Remove old steamcmd directory.
# Create Directory
echo -e "$YELLOW Creating the SteamCMD directory. $RESET"
sleep 0.5s; mkdir steamcmd
echo -e " Directory created, moving forward."
cd steamcmd; sleep 1s

# Install Lib32GCC1
echo -e; echo -e "$YELLOW Installing linux steam dependencies. $RESET"
sudo apt-get install lib32gcc1
echo -e " Lib32gcc1 is installed."
sleep 0.5s

# Install SteamCMD
echo -e; echo -e "$YELLOW Installing SteamCMD $RESET"
curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz -o steamcmd_linux.tar.gz -#
tar -xvzf steamcmd_linux.tar.gz
echo -e; sleep 0.5s

# Install Server Files
echo -e "$YELLOW SteamCMD Installed. Now installing game server. This may take a while. $RESET"
./steamcmd.sh +login anonymous +force_install_dir ../ +app_update $gameid validate +quit

echo -e; sleep 0.5s
echo -e "$GREEN Complete. Exiting. $RESET"
echo -e " You may now start the server with $GREEN ./arkserver.sh start $RESET"
