#!/bin/bash

# Version Checker 
version="1.2.0"

source ../version.ini
source ../version_game.ini
source ../configuration.ini
source formatting.ini

source _functions

# Version Checker
echo -e; echo -e "$YELLOW Checking version with github. $RESET"
if [ $version != $installserver ]; then
    echo -e " Script update available! (Install Script)"
    echo -e; echo -e "$YELLOW Downloading script file. $RESET"
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/installserver -o installserver -#
    echo -e; echo -e "$GREEN File overwritten. Please restart the script. $RESET"
    exit 0
else
    echo -e " Up to date!"; echo -e
    sleep 1s
fi

installSteam

# Install Server Files
echo -e "$YELLOW Now installing game server. This may take a while. $RESET"
runSteam 1

echo -e "$GREEN Complete. Exiting. $RESET"
echo -e " You may now start the server with $GREEN ./arkserver.sh start $RESET"
