#!/bin/bash

# Version Checker 
parameters_Current="1.2.3"

function parametersCheck {

    echo -e " Checking parameters."

    # Parameters String
    executeString=""

    # Map Name (must be the first option !!!)
    if [[ -z $MapName ]]; then
        executeString="${executeString}TheIsland"
    else
        executeString="${executeString}${MapName}"
    fi

    # Server
    executeString="${executeString}?listen"

    ########################
    ## Boolean Parameters ##
    ########################

    # Dont Always Notify Player Joined
    AlwaysNotifyPlayerJoined=$(checkBoolean $AlwaysNotifyPlayerJoined false)
    AlwaysNotifyPlayerJoined=$(invertBoolean $AlwaysNotifyPlayerJoined) # Variable is NotifyJoin, Parameter is DontNotifyJoin

    # Always Notify Player Left
    AlwaysNotifyPlayerLeft=$(checkBoolean $AlwaysNotifyPlayerLeft false)

    # Allow Third Person Player
    AllowThirdPersonPlayer=$(checkBoolean $AllowThirdPersonPlayer false)

    # Global Voice Chat
    GlobalVoiceChat=$(checkBoolean $GlobalVoiceChat false)

    # Show Map Player Location
    ShowMapPlayerLocation=$(checkBoolean $ShowMapPlayerLocation false)

    # No Tribute Downloads
    NoTributeDownloads=$(checkBoolean $NoTributeDownloads false)

    # Proximity Chat
    ProximityChat=$(checkBoolean $ProximityChat false)

    # Server PvE
    ServerPVE=$(checkBoolean $ServerPVE false)

    # Server Hardcore
    ServerHardcore=$(checkBoolean $ServerHardcore false)

    # Server Force No Hud
    ServerForceNoHUD=$(checkBoolean $ServerForceNoHUD false)

    # Server Crosshair
    ServerCrosshair=$(checkBoolean $ServerCrosshair false)

    # Enable PvP Gamma
    EnablePvPGamma=$(checkBoolean $EnablePvPGamma false)

    # Disable Structure Decay PvE
    DisableStructureDecayPvE=$(checkBoolean $DisableStructureDecayPvE false)

    # Allow Flyer Carry PvE
    AllowFlyerCarryPvE=$(checkBoolean $AllowFlyerCarryPvE false)

    # Clamp Resource Harvest Damage
    ClampResourceHarvestDamage=$(checkBoolean $ClampResourceHarvestDamage false)

    # Prevent Download Survivors
    PreventDownloadSurvivors=$(checkBoolean $PreventDownloadSurvivors false)

    # Prevent Download Items
    PreventDownloadItems=$(checkBoolean $PreventDownloadItems false)

    # Prevent Download Dinos
    PreventDownloadDinos=$(checkBoolean $PreventDownloadDinos false)

    # RCON Enabled
    if [[ -z $ServerAdminPassword ]]; then
        RconEnabled="false"
    fi
    RconEnabled=$(checkBoolean $RconEnabled false)

    ########################
    ## Integer Parameters ##
    ########################

    # Max Structures In Range
    MaxStructuresInRange=$(checkInteger $MaxStructuresInRange 1300)
    
    # New Max Structures In Range
    NewMaxStructuresInRange=$(checkInteger $NewMaxStructuresInRange 6000)

    # PvE Structure Decay Destruction Period ( Not in GameUserSettings.ini ? )
    PvEStructureDecayDestructionPeriod=$(checkInteger $PvEStructureDecayDestructionPeriod 0)

    # Max Players
    MaxPlayers=$(checkInteger $MaxPlayers 70)

    # Kick Idle Players Period (AFK Timer)
    KickIdlePlayersPeriod=$(checkInteger $KickIdlePlayersPeriod 2400)

    # Auto Save Period Minutes
    AutoSavePeriodMinutes=$(checkInteger $AutoSavePeriodMinutes 15)

    # Port
    GamePort=$(checkInteger $GamePort 7777)
    executeString="${executeString}?Port=${GamePort}"

    # Query Port
    QueryPort=$(checkInteger $QueryPort 27015)
    executeString="${executeString}?QueryPort=${QueryPort}"

    # RCON Port
    RconPort=$(checkInteger $RconPort 32330)

    ########################
    ## Double Parameters  ##
    ########################

    # Day Cycle Speed Scale
    DayCycleSpeedScale=$(checkDouble $DayCycleSpeedScale 1.0)

    # Night Time Speed Scale
    NightTimeSpeedScale=$(checkDouble $NightTimeSpeedScale 1.0)

    # Day Time Speed Scale
    DayTimeSpeedScale=$(checkDouble $DayTimeSpeedScale 1.0)

    # Dino Damage Multiplier
    DinoDamageMultiplier=$(checkDouble $DinoDamageMultiplier 1.0)

    # Tamed Dino Damage Multiplier ( Not in GameUserSettings.ini ? )
    TamedDinoDamageMultiplier=$(checkDouble $TamedDinoDamageMultiplier 1.0)

    # Player Damage Multiplier
    PlayerDamageMultiplier=$(checkDouble $PlayerDamageMultiplier 1.0)

    # Structure Damage Multiplier
    StructureDamageMultiplier=$(checkDouble $StructureDamageMultiplier 1.0)

    # Player Resistance Multiplier
    PlayerResistanceMultiplier=$(checkDouble $PlayerResistanceMultiplier 1.0)

    # Dino Resistance Multiplier
    DinoResistanceMultiplier=$(checkDouble $DinoResistanceMultiplier 1.0)

    # Tamed Dino Resistance Multiplier ( Not in GameUserSettings.ini ? )
    TamedDinoResistanceMultiplier=$(checkDouble $TamedDinoResistanceMultiplier 1.0)

    # Structure Resistance Multiplier
    StructureResistanceMultiplier=$(checkDouble $StructureResistanceMultiplier 1.0)
    
    # XP Multiplier
    XPMultiplier=$(checkDouble $XPMultiplier 1.0)

    # PvE Structure Decay Period Multiplier
    PvEStructureDecayPeriodMultiplier=$(checkDouble $PvEStructureDecayPeriodMultiplier 1.0)

    # Taming Speed Multiplier
    TamingSpeedMultiplier=$(checkDouble $TamingSpeedMultiplier 1.0)

    # Harvest Amount Multiplier
    HarvestAmountMultiplier=$(checkDouble $HarvestAmountMultiplier 1.0)

    # Harvest Health Multiplier
    HarvestHealthMultiplier=$(checkDouble $HarvestHealthMultiplier 1.0)

    # Resources Respawn Period Multiplier
    ResourcesRespawnPeriodMultiplier=$(checkDouble $ResourcesRespawnPeriodMultiplier 1.0)

    # Player Character Water Drain Multiplier
    PlayerCharacterWaterDrainMultiplier=$(checkDouble $PlayerCharacterWaterDrainMultiplier 1.0)

    # Player Character Food Drain Multiplier
    PlayerCharacterFoodDrainMultiplier=$(checkDouble $PlayerCharacterFoodDrainMultiplier 1.0)

    # Player Character Stamina Drain Multiplier
    PlayerCharacterStaminaDrainMultiplier=$(checkDouble $PlayerCharacterStaminaDrainMultiplier 1.0)

    # Player Character Health Recovery Multiplier
    PlayerCharacterHealthRecoveryMultiplier=$(checkDouble $PlayerCharacterHealthRecoveryMultiplier 1.0)

    # Dino Character Food Drain Multiplier
    DinoCharacterFoodDrainMultiplier=$(checkDouble $DinoCharacterFoodDrainMultiplier 1.0)

    # Dino Character Stamina Drain Multiplier
    DinoCharacterStaminaDrainMultiplier=$(checkDouble $DinoCharacterStaminaDrainMultiplier 1.0)

    # Dino Character Health Recovery Multiplier
    DinoCharacterHealthRecoveryMultiplier=$(checkDouble $DinoCharacterHealthRecoveryMultiplier 1.0)

    # Dino Count Multiplier
    DinoCountMultiplier=$(checkDouble $DinoCountMultiplier 1.0)

    # Difficulty Offset
    DifficultyOffset=$(checkDouble $DifficultyOffset 0.2)

    ########################
    ## String Parameters  ##
    ########################
    
    # Multi Home (IP Address)
    if [ ! -z $IpAddress ]; then
        executeString="${executeString}?MultiHome=${IpAddress}"
    fi

    ########################

    # Server
    executeString="${executeString} -server -log"
    
    # "Experiment Fast Load Cache"
    if [[ $UserCache =~ true ]]; then
        executeString="${executeString} -usecache"
    fi


    sleep 1s; echo -e
    echo -e "$YELLOW Check complete, starting server compiling. $RESET"
    
    # Push to server config.
    pushFileSystem
    echo -e; echo -e "$YELLOW Starting Server $RESET"
    echo -e " Executing commandline in screen session named:$YELLOW $ScreenName $RESET"
    
    # Run Server
    cd $GAME_DIR
    #echo " ./$ArkExecute $executeString"
    screen -A -m -d -S $ScreenName ./$ArkExecute $executeString

    echo -e; echo -e "$GREEN Server is starting up. To access the console, relaunch the script and use: ./arkserver.sh view $RESET"
    echo -e; return

}
