#!/bin/bash

# Version Checker 
version="1.0.0"

source ../version.ini
source ../configuration.ini
source formatting.ini

# Compare Versions
echo -e; echo -e "$YELLOW Checking version with github. $RESET"
if [ $version != $serverstatus ]; then
    echo -e " Script update avaibale! (Status Script)"
    echo -e; echo -e "$YELLOW Downloading script file. $RESET"
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/serverstatus -o serverstatus -#
    echo -e; echo -e "$GREEN File overwritten. Please restart the script. $RESET"
    exit 0
else
    echo -e " Up to date!"; echo -e
    sleep 1s
fi


# Couple If Statments for Stats Info
if [ -z $ipAddress ]; then
    address="$RED UNDEFINED $RESET (Default IP Address)"
else
    address="$YELLOW $ipAddress $RESET"
fi

if [-z $arkServers  ]; then
    arkServerList="$RED DISABLED $RESET"
else
    arkServerList="$YELLOW $arkServers $RESET"
fi


# Show Information
echo -e "$YELLOW Collecting status of your Ark server... $RESET"
sleep 0.5s; cd ../
if ps aux | grep -v grep | grep "$arkExecute"; then
    echo -e; sleep 0.5s
    sleep 0.3s; echo -e " Is Server Running:$GREEN YES $RESET"
    sleep 0.3s; echo -e " Executable:$YELLOW $arkExecute $RESET"
    echo -e; sleep 0.3s
    sleep 0.3s; echo -e " Address: $address"
    sleep 0.3s; echo -e " HostName:$GREEN $hostname $RESET"
    sleep 0.3s; echo -e " Server Pass:$YELLOW $serverPass $RESET"
    sleep 0.3s; echo -e " Admin Pass:$YELLOW $adminPass $RESET"
    sleep 0.3s; echo -e " Max Players:$YELLOW $playerCount $RESET"
    sleep 0.3s; echo -e " ArkServers: $arkServerList"
    echo -e; sleep 0.3s
    if [ $showServerSettings = "True" ]; then
        echo -e "#########[ Server Settings ]########"
        sleep 0.3s; echo -e " Show Players on Map:$CYAN         $showPlayers $RESET"
        sleep 0.3s; echo -e " Hardcore Mode:$CYAN               $hardcore $RESET"
        sleep 0.3s; echo -e " Gloabl Voice Chat:$CYAN           $gloablVoice $RESET"
        sleep 0.3s; echo -e " Proximity Chat:$CYAN              $proxChat $RESET"
        sleep 0.3s; echo -e " No Tribute DL:$CYAN               $noTributeDl $RESET"
        sleep 0.3s; echo -e " Allow Third Person:$CYAN          $thirdPerson $RESET"
        sleep 0.3s; echo -e " Notify Leaving:$CYAN              $notifyLeft $RESET"
        sleep 0.3s; echo -e " Dont Ntofiy Join:$CYAN            $dontNotifyJoin $RESET"
        sleep 0.3s; echo -e " PVE Enabled:$CYAN                 $pveServer $RESET"
        sleep 0.3s; echo -e " Enable Crosshairs:$CYAN           $crossHair $RESET"
        sleep 0.3s; echo -e " No HUD:$CYAN                      $noHud  $RESET"
        sleep 0.3s; echo -e " Enable PvP Gamma:$CYAN            $enablePvPGamma $RESET"
        sleep 0.3s; echo -e " AFK Timer:$CYAN                   $afkTimer Seconds $RESET"
        sleep 0.3s; echo -e " Auto Save:$CYAN                   $autoSave Minutes $RESET"
        sleep 0.3s; echo -e " Difficulty Multiplier:$CYAN       $difficulty $RESET"
        sleep 0.3s; echo -e " Current Map:$CYAN                 $map $RESET"
    fi
    if [ $showServerMutipliers = "True" ]; then
        sleep 0.3s; echo -e "#######[ Server Multipliers ]#######"
        sleep 0.3s; echo -e " TamingSpeed:$CYAN                 $TamingSpeedMultiplier
        sleep 0.3s; echo -e " HarvestAmount:$CYAN               $HarvestAmountMultiplier
        sleep 0.3s; echo -e " PlayerWaterDrain:$CYAN            $PlayerCharacterWaterDrainMultiplier
        sleep 0.3s; echo -e " PlayerFoodDrain:$CYAN             $PlayerCharacterFoodDrainMultiplier
        sleep 0.3s; echo -e " DinoFoodDrain:$CYAN               $DinoCharacterFoodDrainMultiplier
        sleep 0.3s; echo -e " PlayerStaminaDrain:$CYAN          $PlayerCharacterStaminaDrainMultiplier
        sleep 0.3s; echo -e " DinoStaminaDrain:$CYAN            $DinoCharacterStaminaDrainMultiplier
        sleep 0.3s; echo -e " PlayerHealthRecovery:$CYAN        $PlayerCharacterHealthRecoveryMultiplier
        sleep 0.3s; echo -e " DinoHealthRecovery:$CYAN          $DinoCharacterHealthRecoveryMultiplier
        sleep 0.3s; echo -e " DinoCount:$CYAN                   $DinoCountMultiplier
        sleep 0.3s; echo -e " HarvestHealth:$CYAN               $HarvestHealthMultiplier
        sleep 0.3s; echo -e " PvEStructureDecayPeriod:$CYAN     $PvEStructureDecayDestructionPeriod
        echo -e; sleep 0.3s
        sleep 0.3s; echo -e " MaxStructuresInRange:$CYAN        $MaxStructuresInRange
        sleep 0.3s; echo -e " DayCycleSpeedScale:$CYAN          $DayCycleSpeedScale
        sleep 0.3s; echo -e " NightTimeSpeedScale:$CYAN         $NightTimeSpeedScale
        sleep 0.3s; echo -e " DayTimeSpeedScale:$CYAN           $DayTimeSpeedScale
        sleep 0.3s; echo -e " DinoDamage:$CYAN                  $DinoDamageMultiplier
        sleep 0.3s; echo -e " TamedDinoDamage:$CYAN             $TamedDinoDamageMultiplier
        sleep 0.3s; echo -e " PlayerDamage:$CYAN                $PlayerDamageMultiplier
        sleep 0.3s; echo -e " StructureDamage:$CYAN             $StructureDamageMultiplier
        sleep 0.3s; echo -e " PlayerResistance:$CYAN            $PlayerResistanceMultiplier
        sleep 0.3s; echo -e " DinoResistance:$CYAN              $DinoResistanceMultiplier
        sleep 0.3s; echo -e " TamedDinoResistance:$CYAN         $TamedDinoResistanceMultiplier
        sleep 0.3s; echo -e " StructureResistance:$CYAN         $StructureResistanceMultiplier
        sleep 0.3s; echo -e " XPMultiplier:$CYAN                $XPMultiplier
    fi
fi
