#!/bin/bash

# Version Checker 
updateserver_Current="1.2.4"

# Update Server
function updateServer {

    echo -e; echo -e "$YELLOW Preparing to stop the server. $RESET"
    sleep 0.5s
    if screen -list | grep -q $ScreenName; then
        echo -e " Server is running, now stopping."
        screen -S $ScreenName -X quit
        echo -e " Session stopped. Removing PID's"
        PID=`pgrep -f $ArkExecute`
        kill -9 $PID
        sleep 0.5s
        echo -e " PID's removed"
        echo -e; sleep 0.5s
        echo -e "$RED Server stopped $RESET"
    else
        echo -e " Server is offline. Moving on."
    fi

    echo -e; sleep 0.5s

    installSteam

    cd $STEAM_DIR
    echo -e; sleep 0.5s
    echo -e "$YELLOW Now updating the server. This may take a while. $RESET"
    runSteam 1

    cd $GAME_DIR
    echo -e; sleep 0.5s
    echo -e "$YELLOW Making sure old executable is removed. $RESET"
    sleep 0.5s
    if [ -f $ArkExecute ] && [ $ArkExecute != $GAME_EXECUTABLE ]; then
        echo -e "$ERR Old executable found, removing it. $RESET"
        rm $ArkExecute
        sleep 0.5s
        if [ -f $ArkExecute ]; then
            echo -e; echo -e "$ERR Unable to delete old executable. $RESET"
            echo -e " Please remove the file named$YELLOW $ArkExecute$RESET."
        else
            echo -e " Old executable removed. Moving on."
        fi
    else
        echo -e " Old executable not found."
    fi

    echo -e; sleep 0.5s
    echo -e "$GREEN Server update complete. $RESET"
    echo -e; sleep 0.5s
    echo -e "$YELLOW Please restart the script to start the server. $RESET"
    return

}
