#!/bin/bash

# Version Checker 
version="1.1.6"

source ../version.ini
source ../configuration.ini
source formatting.ini

# Version Checker
echo -e; echo -e "$YELLOW Checking version with github. $RESET"
if [ $version != $viewserver ]; then
    echo -e " Script update avaibale! (Stop Script)"
    echo -e; echo -e "$YELLOW Downloading script file. $RESET"
    curl https://raw.githubusercontent.com/Zendrex/ARK-Linux-Server-Script/master/.serverscript/viewserver -o viewserver -#
    echo -e; echo -e "$GREEN File overwritten. Please restart the script. $RESET"
    exit 0
else
    echo -e " Up to date!"; echo -e
    sleep 1s
fi

echo -e " Checking if server session exists..."
sleep 0.5s
if screen -list | grep -q "$sessionName"; then
    echo -e
    echo -e "$GREEN Server Is Running! $RESET"
    sleep 0.5s
    echo -e "$YELLOW To detach from the session, hold CTRL+A+D (in that order) $RESET"
    echo -e; sleep 0.5s
    echo -e "$YELLOW You will be brought to the session in 10 seconds. $RESET"
    echo -e
    sleep 10s
    screen -r $sessionName
else
  echo -e "$ERR Unable to find the server session. Script is assuming the server isnt running."
  exit 0
fi
